### ISSUE TITLE
Addons with spaces

### ISSUE THREAD

**Issue by ghost** [Marakuja/UpdateAddons#1]
Thanks for making this!

I can't seem to get addons with spaces in the name to work. Specifically the addon: https://wow.curseforge.com/projects/azeroth-auto-pilot with columns of: 

Azeroth Auto Pilot | curseforge | azeroth-auto-pilot
-- | -- | --

Results in:

```
Azeroth - Auto - azeroth-auto-pilot
Exception calling "DownloadString" with "1" argument(s): "Could not find a part of the path
'C:\Users\Frore\Desktop\UpdateAddons-master\code\Auto\wow\addons\azeroth-auto-pilot\download'."
At C:\Users\Frore\Desktop\UpdateAddons-master\code\updateaddons.ps1:189 char:5
+     $html = $wc.DownloadString("$urlBase/wow/addons/$uid/download")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

ERROR PARSING CURSEFORGE HTML!
```
I can get further by changing the columns to:

Azeroth+Auto+Pilot | curseforge | azeroth-auto-pilot
-- | -- | --

Which seems to let me download the file, but then I run into path issues:

```
Azeroth+Auto+Pilot - http://www.curseforge.com - azeroth-auto-pilot
        Update required: Remote ver=2611885
        Downloading http://www.curseforge.com/wow/addons/azeroth-auto-pilot/download/2611885/file...
        done.
        Extracting Archive...
        done.
        Deleting file...
        done.
Set-Content : Could not find a part of the path 'D:\Blizzard\World of
Warcraft\Interface\Addons\Azeroth+Auto+Pilot\PSUpdateAddons.state'.
At C:\Users\Frore\Desktop\UpdateAddons-master\code\updateaddons.ps1:213 char:9
+         Set-Content -Value $currentUrl -Path $stateFilePath -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Blizzard\Wor...ateAddons.state:String) [Set-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand
```

I can go into the AddOns directory and manually add a + instead of spaces, but when the addon is extracted it is replaced by the correct "with spaces" folder.

**Comment by Marakuja** [comment]
Hi and thanks for using this tool :)

I will have a look into it, I just hadn't thought (or tested) addons that have spaces in their names specifically.

**Comment by Marakuja** [comment]
Please try the new version 0.1.1 you get from the [releases](https://github.com/Marakuja/UpdateAddons/releases) in my project. Spaces in addon names should now work correctly.

**Comment by ghost** [comment]
Works perfect!
