### ISSUE TITLE
Error 403 updating from curse

### ISSUE THREAD

**Issue by Magissia** [Marakuja/UpdateAddons#2]
I get an error 403 line 17 with this CSV

Name,Source,UID
BigWigs,curseforge,big-wigs
GTFO,curseforge,gtfo

**Comment by Marakuja** [comment]
Thanks for the message. Unfortunately I get the same error when curseforge has its cloudflare DDoS protection thing up. That prevents my scripts to get the page and throws an html error

You have to wait until curse lowers their protection again. There is nothing i found until now that let me bypass this limitation.

You can use the wowinterface website normally as they do not use a DDoS protection on their site.

**Comment by Magissia** [comment]
Never seen curse without that "DDoS" protection since they implemented it.
Guess it's time to bug every devs to put their addons on wowinterface then.
